### ISSUE TITLE
Aruco detection

### ISSUE THREAD

**Issue by decamargo10** [AAU-Space-Robotics/rover-software#10]

**Comment by decamargo10** [comment]
Timeline: 20th february

**Comment by Hamza-Robotics** [comment]
Aruco marker detector finished. There is a node to publish a pseudo camera feed and the aruco marker detector node takes the aruco markers, detects them and then publishes a list of all aruco markers with ID, position and orientation in the camera frame. What is missing is the camera calibration values and the size of the aruco marker.
