### ISSUE TITLE
Research grasp planning / grasping strategy

### ISSUE THREAD

**Issue by abmoRobotics** [AAU-Space-Robotics/rover-software#13]

**Comment by Hamza-Robotics** [comment]
[https://aaudk.sharepoint.com/:w:/r/sites/AAUSpaceRoboticsTeamCompetition/Delte%20dokumenter/Software%20Team/Grasping%20Research/Robotic%20Grasping%20from%20Classical%20to%20Modern%20A%20survery%20(SUMMERY).docx?d=wd46869ac9cd64baaa08933fede810f1d&csf=1&web=1&e=E6HElc](url)
